@startuml

start

#DarkSeaGreen:  init |

#Olive: crontab |

stop


start

#palegreen: **Start ** ;
floating note left: Логика настройки
note right
Два этапа:
* Начальная настройка
====
* Постоянное использование
** Использование с разработкой
** Использование без разработки
end note

#HotPink: начало использования;

partition " controlpath.sh " {

#GREEN: Читаем AdminScriptVar  кофнигурационный файл
====
USERBOT=""
PATHFLASH=""
NAMEPROJECT=$USERBOT
PATHCONFBOT="/home/$SUDO_USER/source/adminscript/conf"
HOMEADMIN="/home/${USERBOT}/source/adminscript"
HOMECRON="/home/${USERBOT}/source/crontabconf"
HOMELOG="/home/${USERBOT}/log"
MODEBOT="USE"
=====
# AWS - запущен на AWS
# USE - использование
# DEV - разботка
# OFF - выключен;


note right
Динамический конфигурационный файл
Переменная PATHKEY опеределяется автоматически
end note


if ( есть название флешки в PATHFLASH ? ) then (ДА)
:читаем данные с директории
на флешке в переменной PATHKEY
====
PATHKEY=/mnt/$PATHFLASH/$USERBOT;
else (НЕТ)
:читаем данные с директории
локально в переменной PATHKEY
====
PATHKEY=/home/$USERBOT/source/${NAMEPROJECT}/conf;
endif

}

fork

while (\nпроверяем crontab \n каждые 15 мин <b>ngrok.sh</b> \n) is (YES)


partition " ngrok.sh " {

#GREEN: controlpath.sh
перечитываем конфигурацию;

#RED:Выключаем ngrok;


if (Бот на AWS?) then (ДА)
: Режим бот на AWS./
#YELLOW: Не запускаем ngrok;

elseif (Режим использования) then (ДА)
: Режим использования./
#GREEN:Запускаем ngrok;

elseif (Режим разработки) then (ДА)
: Режим разработки./
#GREEN:Запускаем ngrok;

else (Ничего)

: Режим бот выключен./
#YELLOW: Не запускаем ngrok;

endif


}

endwhile (NO)

fork again

while (\nпроверяем crontab \n каждые 5 мин <b>gitnodejs.sh</b>\n) is (YES)

partition " gitnodejs.sh " {

#GREEN: controlpath.sh
перечитываем конфигурацию;

#RED:Выключаем node;


if (Бот на AWS?) then (ДА)
: Режим бот на AWS./
#YELLOW: Не запускаем git;
#YELLOW: Не запускаем nodejs;
elseif (Режим использования) then (ДА)
: Режим использования./
#YELLOW: Не запускаем git;
#GREEN:Запускаем nodejs;
elseif (Режим разработки) then (ДА)
: Режим разработки./
#GREEN:Запускаем git;
#GREEN:Запускаем nodejs;
else (Ничего)
: Режим бот выключен./
#YELLOW: Не запускаем git;
#YELLOW: Не запускаем nodejs;
endif


}

endwhile (NO)


end fork


-[#green,dashed]-> ла ла;


stop

@enduml
